### ISSUE TITLE
Diseases context definition and displaying

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/okdose-dapp#5]
ℹ️ This issue is an Epic 🎯

## Context

The OKDOSE primary information is the diseases that are available for its calculation, hence is required to create the following group of data:

- Transmission Mediums
- Diseases
- Diseases Types

It is required to create the relations between this information according as follows:

Transmission Medium → Disease → Disease Type

Mycobacterias → Leprosy → Multibacillary

## Objective
Create the data for each Disease using prototypes(key/value), the data structure is composed of the next representational example:

```javascript
diseases = {
	transmissionMedimumName: {
		diseaseOneName: {
			name: "Name One"
			diseaseTypes: [
				diseaseTypeOneName: {name: "Name One Type"}
				diseaseTypeTwoName: {name: "Name Two Type"}
			]
		},
		diseaseTwoName: {
			name: "Name Two",
		},
		...
		diseaseNName: {
		}
	}

```

If the Disease does not have any Diseases types, just leave the basic information.

## Checklist

- [ ] Implement the information for the Transmission Medium “Vectors”
- [ ] Implement the information for the Transmission Medium “Zoonoses”
- [ ] Implement the information for the Transmission Medium “Mycobacteria”
